# Generated by Django 4.2.3 on 2023-08-29 09:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('Eventprice', models.CharField(max_length=50)),
                ('eventname', models.CharField(max_length=100)),
                ('teacherimage', models.FileField(default=None, null=True, upload_to='Events')),
                ('teachername', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
