# Generated by Django 4.2.3 on 2023-08-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classimage', models.ImageField(default='class.png', upload_to='static/images/classes/class')),
                ('classtitle', models.CharField(max_length=1000)),
                ('classtime', models.CharField(max_length=500)),
                ('classteacherimage', models.ImageField(default='teacher.png', upload_to='static/images/classes/teacher')),
                ('classteachername', models.CharField(max_length=50)),
                ('classprice', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
