# Generated by Django 4.2.3 on 2023-08-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='classimage',
            field=models.ImageField(default='None', upload_to='media/images/classes/class'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='classteacherimage',
            field=models.ImageField(default='None', upload_to='media/images/classes/teacher'),
        ),
    ]
