# Generated by Django 4.2.3 on 2023-08-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0002_alter_classes_classimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='classimage',
            field=models.FileField(default=None, null=True, upload_to='classes/class'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='classteacherimage',
            field=models.FileField(default=None, null=True, upload_to='classes/teacher'),
        ),
    ]
