# Generated by Django 4.2.3 on 2023-08-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_image', models.ImageField(default='teacher.jpg', upload_to='static/images/teachers')),
                ('teacher_name', models.CharField(max_length=100)),
                ('teacher_designation', models.CharField(max_length=200)),
            ],
        ),
    ]
