# Generated by Django 4.2.3 on 2023-08-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_image',
            field=models.FileField(default=None, null=True, upload_to='teachers'),
        ),
    ]
