# Generated by Django 4.2.3 on 2023-08-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassesEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('Classes', models.CharField(choices=[('', 'Class'), ('Hospitality, Leisure & Sports Courses', 'Hospitality, Leisure & Sports Courses'), ('Environmental Studies & Earth Sciences', 'Environmental Studies & Earth Sciences'), ('Natural Sciences & Mathematics Courses', 'Natural Sciences & Mathematics Courses'), ('Basic English Speaking and Gramer', 'Basic English Speaking and Gramer')], max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
